defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data_params:
  prompt_type: "real"
  num_data_points: "1M"

exp:
  model: resnet50
  dataset: imagenet
  save_path: "/visinf/home/ksingh/syn-rep-learn/calibration/results/"
  seed: 42
  batch_size: 32
  n_workers: 1
  name: '${model}_${dataset}.json'
  num_bins: 20
  backbone: False
  ablation: False

