defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
data_params:
  prompt_type: "real"
  num_data_points: "1M"

exp:
  model: resnet50
  backbone: False
  dataset_path : '/fastdata/ksingh/robust/focus/'
  in_dataset: imagenet
  ood_dataset: iNaturalist
  batch_size: 32
  n_workers: 4
  score: 'entropy'
  save_path: "/visinf/home/ksingh/syn-rep-learn/ood_detection/results/"
  seed: 42
  ablation: False
