defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data_params:
  prompt_type: "real"
  num_data_points: "1M"


exp:
  model: resnet50
  dataset: 'imagenet'
  base_path: "/fastdata/ksingh/robust/shape_bias/cue-conflict"
  save_path: "/visinf/home/ksingh/syn-rep-learn/shape_bias/results/"
  seed: 42
  batch_size: 32
  n_workers: 4
  name: '${model}_${dataset}.json'
  ablation: False
